[OPENROUTER]
OPENROUTER_API_KEY = "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"

[OPENAI]
OPENAI_API_KEY = "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"

[DEEPSEEK]
DEEPSEEK_API_KEY = "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"
