[OPENROUTER]
OPENROUTER_API_KEY = "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"

[OPENAI]
OPENAI_API_KEY = "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"

[DEEPSEEK]
DEEPSEEK_API_KEY = "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"
